version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot-app
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      TELEGRAM_BOT_TOKEN: YOUR_BOT_TOKEN
  db:
    image: mysql:5.7
    container_name: telegram-bot-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telegram_bot